### ISSUE TITLE
VDW toevoegen aan de scheduler

### ISSUE THREAD

**Issue by AxlVanAlboom** [ISyE-FM/Planning#154]
```[tasklist]
### Tasks
- [x] setup just planit for VDW
- [x] OS - WM mapping
- [x] taskMapper
- [ ] https://github.com/ISyE-FM/Planning/issues/188
```
