### ISSUE TITLE
add present m5/3 to VDW schedule

### ISSUE THREAD

**Issue by AxlVanAlboom** [ISyE-FM/Planning#188]
```[tasklist]
### Tasks
- [x] check for ultrasmall robot together with tool --> cell kan execute screw M3/M5
- [x] ultrasmall robot available enough as check?
- [x] make WD/JO for present M5/3
- [x] WD uses addon instead of cell
- [x] all WD uses Robot instead off cell
```
