### ISSUE TITLE
JPI settings instelbaar

### ISSUE THREAD

**Issue by AxlVanAlboom** [ISyE-FM/Planning#200]
```[tasklist]
### Tasks
- [ ] https://github.com/ISyE-FM/Planning/issues/202
- [x] API settings manipulation
- [x] JPI settings DB
```
